### ISSUE TITLE
Roon Bridge on Coreelec device - Mecool K3 Pro

### ISSUE THREAD

**Issue by Martynet** [dubo-dubon-duponey/docker-roon#13] opened 2021-12-01 10:37 UTC
Hi,
I have Synology NAS, running Roon server. And it's working great. I can access it from all my devices, no issues.
I bought a new DAC for living room and before I spend money for music streamer device or raspberry pie, I decided to try installing "Roon bridge" in Mecool KIII Pro box, running CoreElec OS. I installed Docker, then Portainer, Watchover and finally Roon Bridge.
So, Roon Bridge container is up and running, but It's not visible to Roon server for some reason.
This is the command I used deploying it:
docker run --name RoonBridge --net=host -e TZ=Europe/Dublin -d -v /storage/.config/docker/roon:/var/roon dubodubonduponey/roon-bridge:latest

Log:
00:00:00.015 Warn: get lock file path: /tmp/.rnbgem0-
00:00:00.369 Trace: [childprocess] using unix child process
Initializing
00:00:00.558 Info: Starting /boot/bin/RoonBridge/Bridge/RoonBridgeHelper
00:00:00.588 Info: ConnectOrStartAndWaitForExit RAATServer, path: /boot/bin/RoonBridge/Bridge/RAATServer
Not Running (.o)
00:00:00.034 Warn: get lock file path: /tmp/.rnbhgem0-
Running

Thank you for any help with this

**Comment by dubo-dubon-duponey** [comment] 2021-12-01 17:34
Hi @Martynet 

> docker run --name RoonBridge --net=host -e TZ=Europe/Dublin -d -v /storage/.config/docker/roon:/var/roon dubodubonduponey/roon-bridge:latest

This ^ is not the command I provided in the README, right?

Is there a reason why you are using this instead and removed the other options?

**Comment by dubo-dubon-duponey** [comment] 2021-12-01 18:08
So, unless you had good reasons to use your own command, you should really start with using the right command instead.

If that still does not work, you very likely have a networking problem:
1. what *EXACT* command did you use to start roon **server**?
2. is your Roon server on the same vlan as your Roon bridge?
3. do you believe mDNS / bonjour / zeroconf is working fine on your lan, between your server and bridge?
4. does CoreElec have any sort of firewalling / fancy networking that would prevent multicast from working?

**Comment by Martynet** [comment] 2021-12-01 19:30
Hi, thank you for quick reply. Sorry, I didn't look in readme previously. So now I did and found this:
docker run -d \
    --net host \
    --name bridge \
    --read-only \
    --cap-drop ALL \
    --group-add audio \
    --device /dev/snd \
    --rm \
    ghcr.io/dubo-dubon-duponey/roon-bridge
    
    
    But if I try that, I just get an error:
    Unable to find image 'ghcr.io/dubo-dubon-duponey/roon-bridge:latest' locally
docker: Error response from daemon: Get https://ghcr.io/v2/dubo-dubon-duponey/roon-bridge/manifests/latest: unauthorized.
See 'docker run --help'.

1. docker run --name RoonBridge --net=lsio -e TZ=Europe/Dublin -d -v /storage/.config/docker/roon:/var/roon dubodubonduponey/roon-bridge:latest

2. Yes, all my devices are on the same network and can see each other. CoreElec is basically light Linux with KODI layer on top. You install Docker as an add-on and then you can install images from KODI environment through "CoreElec - linuxserver.io" repository. There's things like Plex server, TVHeadednd, NetData etc... I have few of these installed and all working fine - Portainer and Netdata.

3. Communication should be fine. I'm running LOTS of images in Docker in my Synology server, where Roon server is running. There's for example Navidrome music server which I can connect to from CereElec perfectly. Everything just works between all my servers and clients.

4. No.

One of my friends, who is familiar with Docker much more than me, think that the problem is permissions of some sort...

Thank you for all the help.

**Comment by dubo-dubon-duponey** [comment] 2021-12-01 20:22
You can just use "dubodubonduponey/roon-bridge" instead of ghcr.io/dubo-dubon-duponey/roon-bridge if you can't m/won't authenticate with ghcr.

**Comment by dubo-dubon-duponey** [comment] 2021-12-01 20:23
1. The way you start roon server is unlikely to work. Roon need host or macvlan networking for its discovery mechanism to work

**Comment by dubo-dubon-duponey** [comment] 2021-12-01 20:26
2. Roon relies on multicast for discovery. This is very different from a networking perspective. This is not the same thing as being able to access an http server on another machine. So, are you positive *mDNS* reolution works between these two machines?

**Comment by dubo-dubon-duponey** [comment] 2021-12-01 20:27
3. As stated above, the fact that other containers "work" is no guarantee - the issue is networking here

**Comment by dubo-dubon-duponey** [comment] 2021-12-01 20:30
Summarizing:
- start the bridge with the provided command from the readme (feel free to use the hub version instead of the ghcr version if you prefer)
- make *sure* you start the *server* in host or macvlan networking (no other networking mode will work)

If you do these two and it still does not work, we can try to debug this further.

Also, it's unlikely that your problem is a permission problem.

Hope that helps.

**Comment by Martynet** [comment] 2021-12-01 20:31
Thank you, will try now

**Comment by dubo-dubon-duponey** [comment] 2021-12-01 20:31
Re reading your answer to question 1: this is the bridge command line, not the server one.

**Comment by Martynet** [comment] 2021-12-01 20:39
2. I'm not 100% sure about that, because I don't know how to test it. But, there's Airplay active on CoreElec device and Roonserver can see it and it works. Does that help answer your question?

**Comment by Martynet** [comment] 2021-12-01 20:42
I am trying to install Bridge, not the server

**Comment by Martynet** [comment] 2021-12-01 20:43
so the command line for Bridge is right. Bridge Server is already running and working on Synology NAS and I can access it from my Mac with Roon app and iOS devices.

**Comment by dubo-dubon-duponey** [comment] 2021-12-01 20:44
You still need RoonServer, and you still need it to be started with the right networking mode, otherwise you will not see your bridge - hence my question.

**Comment by Martynet** [comment] 2021-12-01 20:45
You mean another RoonServer? Not just the one on Synology?

**Comment by dubo-dubon-duponey** [comment] 2021-12-01 20:47
I mean the one server you already have.
Can you just copy the exact command you used to start it?

**Comment by Martynet** [comment] 2021-12-01 20:52
Trying now

**Comment by Martynet** [comment] 2021-12-02 09:01
Docker stopped working altogether... Even Portainer and Netdata don't work anymore. When typing command Docker ps, it's empty... I think I installed and removed that RoonBridge so many times, that it just got tired of me...  I don't have the strength to reinstall the CoreElec so I'm giving up on this and I ordered 2012 Mac mini from eBay to run the RoonBridge.

**Comment by dubo-dubon-duponey** [comment] 2021-12-02 20:42
> Docker stopped working altogether... 
> Even Portainer and Netdata don't work anymore. When typing command Docker ps, it's empty... I think I installed and removed that RoonBridge so many times, that it just got tired of me... I don't have the strength to reinstall the CoreElec so I'm giving up on this and I ordered 2012 Mac mini from eBay to run the RoonBridge.

Ok. Wishing you better luck with that one then.
I'm going to close this ticket then.

**Closed as completed by dubo-dubon-duponey** 2021-12-02 20:42 UTC
